### ISSUE TITLE
PDF File location change

### ISSUE THREAD

**Issue by CausticD** [mb243/SynoDL#1]
It looks like the file location has changed. The V3 one is still available here:

http://download.synology.com/download/Document/FAQ/Synology_Download_Station_Official_API_V3.pdf

But a (slightly) newer one is here:

http://download.synology.com/download/Document/DeveloperGuide/Synology_Download_Station_Web_API.pdf

**Comment by mb243** [comment]
I've mentioned this in the README and script itself, though I haven't reviewed the doc for any needed code changes. Thanks!
