### ISSUE TITLE
Erreur line 37 Authenticating to API

### ISSUE THREAD

**Issue by Flavien06** [mb243/SynoDL#2]
Hi I have this error 
> Verifying API ... ok
> Authenticating to API ... /volume1/SynoDL/synodl.sh: command substitution: line 37: unexpected EOF while looking for matching `"'
> /volume1/SynoDL/synodl.sh: command substitution: line 38: syntax error: unexpected end of file
> fail

` SID=`wget -qO - "$SYNO/webapi/auth.cgi?api=SYNO.API.Auth&version=2&method=login&account=$USER&passwd=$PASS&session=DownloadStation&format=sid" | grep 'sid' | awk -F" '{print $6}'``

The error is not with "awk ..." ? It is not awk -F":" ?

**Comment by mb243** [comment]
Should be fixed in 27a7d97. Can you check again and let me know?

**Comment by Flavien06** [comment]
Ok thank is good now 👍
